name: esm-vfc
channels:
  - conda-forge
dependencies:
  - python=3
  - basemap
  - cartopy
  - cartopy_offlinedata
  - dask
  - dask-labextension
  - datashader
  - distributed
  - fsspec
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - jupyter-server-proxy
  - lz4
  - matplotlib-base
  - nbgitpuller
  - netcdf4
  - nomkl
  - numcodecs
  - numpy
  - pandas
  - panel
  - pip
  - python-blosc
  - scipy
  - seaborn
  - xarray
  - xgcm
  - xhistogram
  - zarr
