name: esm-vfc
channels:
  - conda-forge
dependencies:
  - python=3.7
  - basemap
  - cartopy
  - cartopy_offlinedata
  - cmocean
  - cmaps
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - distributed
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - joblib
  - jupyter-server-proxy
  - jupytext
  - lz4
  - matplotlib-base
  - nbval
  - nbgitpuller
  - netcdf4
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - panel
  - pip
  - pyfesom2
  - pyresample
  - pytest
  - python-blosc
  - scipy
  - seaborn
  - seawater
  - shapely
  - xarray
  - xgcm
  - xhistogram
  - xpublish
  - zarr
  - pip:
    - git+https://github.com/intake/filesystem_spec.git@644cc3ac8171c68aab1835483443dfa90d5d7988
    - git+https://github.com/ESM-VFC/esm-vfc-catalogs.git@v2020.05.30.1
    - git+https://github.com/ESM-VFC/intake_pangaeapy.git@v0.1.1
    - git+https://git.geomar.de/python/xorca_lonlat2ij.git@v1.0.0
    - pangaeapy
