name: repo2docker build

on: [push]
#   push:
#     branches:
#       - master

env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_PREFIX: esmvfc/

jobs:
  latest_image:
    env:
      IMAGE: esm-vfc-stacks
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set Job Environment Variables
      run: |
        DOCKER_TAG="${GITHUB_REF}_${GITHUB_SHA}"
        IMAGE_SPEC="${IMAGE_PREFIX}${IMAGE}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"
    - name: Set Up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install repo2docker
      run: |
        python --version
        pip install jupyter-repo2docker docker
        repo2docker --version
        docker version
    - name: Build with repo2docker
      run: |
        jupyter-repo2docker --image-name ${IMAGE_SPEC} --user-name jovyan --no-run .
    - name: Authenticate with DockerHub
      run: |
        echo ${{ secrets.docker_access_token }} | docker login -u ${{ secrets.docker_user_name }} --password-stdin
    - name: Push Image
      run: |
        docker push $IMAGE_SPEC
